name: Crawl Trade
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'
jobs:
  deploy:
    name: Crawl Trade
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt && python3 trade_crawler.py
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}